### ISSUE TITLE
Help with writing Learning Trail

### ISSUE THREAD

**Issue by Chovin** [FreeCodeCampGuam/FreeCodeCampGuamHelp#6]
I think we should designate one main person to write these up.
Who wants to do it? :smile: 
We'll help out of course.

**Comment by rianajade** [comment]
What is Learning Trail?

**Comment by Chovin** [comment]
I just put up a [description](https://github.com/Chovin/FreeCodeCampGuamHelp/blob/master/MeetingNotes/5-6.md) of it.
Feel free to spiff it up if you'd like to.
In fact feel free to spiff up anything you find here :+1:

**Comment by Chovin** [comment]
perfect place to link the [project team sheet](https://github.com/Chovin/FreeCodeCampGuamHelp/blob/master/CampsiteAlpha/Project%20Team.md).

**Comment by Chovin** [comment]
actually, moved to #5
